version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./model:/app/model
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MODEL_PATH=/app/model/saved_models/plant_disease_mobilenet.h5
      - LABEL_JSON_PATH=/app/model/labels/class_names.json
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
